//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCompany_Salchuk_Matyukhina_322
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }

        private static Entities _context;

        public static Entities GetContext()
        {
            if (_context == null) _context = new Entities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Debt> Debts { get; set; }
        public virtual DbSet<OtchetPoOplate> OtchetPoOplates { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<SpisokJilogoFonda> SpisokJilogoFondas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
