//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCompany_Salchuk_Matyukhina_322
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtchetPoOplate
    {
        public int PaymentId { get; set; }
        public int Owner { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Apartment { get; set; }
        public string Period { get; set; }
        public decimal Accrued { get; set; }
        public Nullable<decimal> Paid { get; set; }
    
        public virtual Apartment Apartment1 { get; set; }
        public virtual Owner Owner1 { get; set; }
    }
}
