//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementCompany_Salchuk_Matyukhina_322
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisokJilogoFonda
    {
        public int Fond_id { get; set; }
        public string Adress { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Floors { get; set; }
        public Nullable<int> Apartament { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Square { get; set; }
    }
}
